Enabled xdebug

diff --git a/php/Dockerfile b/php/Dockerfile
--- a/php/Dockerfile
+++ b/php/Dockerfile
@@ -1,6 +1,18 @@
-FROM php:8.1-fpm-alpine
+FROM php:8.1-fpm-alpine as app
 
-RUN docker-php-ext-install pdo pdo_mysql
+
+# Useful PHP extension installer image, copy binary into your container
+
+COPY --from=mlocati/php-extension-installer /usr/bin/install-php-extensions /usr/local/bin
+
+# install php extensions
+# exit on errors, exit on unset variables, print every command as it is executed
+
+RUN set -eux; \
+    install-php-extensions pdo pdo_mysql;
+
+
+#RUN docker-php-ext-install pdo pdo_mysql
 
 # allow super user - set this if you use Composer as a
 # super user at all times like in docker containers
@@ -25,3 +37,29 @@ COPY ./app .
 
 # run composer dump-autoload --optimize
 RUN composer dump-autoload --optimize
+
+
+FROM app as app_dev
+
+
+
+ENV XDEBUG_MODE=off
+
+
+# Copy xdebug config file into container
+
+COPY ./php/conf.d/xdebug.ini /usr/local/etc/php/conf.d/xdebug.ini
+
+# Install xdebug
+
+RUN set -eux; \
+    install-php-extensions xdebug
+
+
+
+
+
+
+
+
+
